#Stage 1
FROM node as build
WORKDIR /apps
COPY ./UrlShortenerFrontend/. .
RUN npm install
COPY . /apps/
ARG configuration=production
RUN npm run build

#stage 2
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY ./UrlShortenerFrontend/nginx.conf /etc/nginx/conf.d/
COPY --from=build /apps/dist/ /usr/share/nginx/html/




# # Stage 1

# FROM node:10-alpine as build-step

# RUN mkdir -p /app

# WORKDIR /app

# COPY package.json /app

# RUN npm install

# COPY . /app

# RUN npm run build --prod

# # Stage 2

# FROM nginx:1.17.1-alpine

# COPY --from=build-step /app/docs /usr/share/nginx/html
