#Stage 1
FROM node as build
WORKDIR /apps
COPY ./UrlShortenerFrontend/. .
RUN npm install
COPY . /apps/
ARG configuration=production
RUN npm run build

#stage 2
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
EXPOSE 80/tcp
COPY ./UrlShortenerFrontend/nginx.conf /etc/nginx/conf.d/nginx.conf
COPY --from=build /apps/dist//url-shortener-frontend/ /usr/share/nginx/html/